# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: I'M OPPIH
description: Just another blog from oppih.
keywords: Jekyll Theme, blog, oppih
url: http://blog.oppih.me
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 生活随笔
    url: /journal
  - text: 技术
    url: /tech
  - text: 「调」皮
    url: /leathercraft
  #- text: 哩哩
  #  url: /lele
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 链接
    url: /links.html

#Author config
author:
    name: oppih
    email: letwego28@gmail.com
    imageLink: http://tp3.sinaimg.cn/1667994270/180/5618832708/1
    simpleIntro: 我是「oppih」，可以叫我「欧皮君」，一个手艺人。
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>
      <p>很早之前，使用过 wordpress 来写博客。但是还要处理很多的底层问题。而使用 Jekyll 来写博客，可以很简单，写 Markdown 就好。然而，Jekyll 还很年轻，没有很多主题的支持。这里的主题，就是为 Jekyll 而写的。希望你能喜欢。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/u/1667994270
  - class: icon-twitter
    url: http://twitter.com/oppih28
  - class: icon-instagram
    url: http://instagram.com/oppih
  - class: icon-stackexchange
    url: http://stackoverflow.com/users/1029157/oppih
  - class: icon-github-alt
    url: http://github.com/oppih

#Links
customLinks:
  - item:
    - text: 本站主题来自「掌心」
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id:

#comment config
disqus:
  config: true
  id: oppih-me

duoshuo:
  config: false
  id: zhanxin
